# Generated by Django 5.1.4 on 2025-01-13 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='photo',
            field=models.ImageField(blank=True, default='employees_photos/default.png', null=True, upload_to='employees_photos/', verbose_name='Фото'),
        ),
    ]
